"""Render an OpenPathAI pipeline as a Colab-ready ``.ipynb``.

The generator is a **pure function**: it takes a pipeline YAML
(either a pre-loaded :class:`Pipeline` or a raw YAML string) plus
optional audit-row metadata, and returns a dict that conforms to
the ipynb schema. :func:`write_notebook` JSON-dumps it.

Phase 11 scope narrowings (see
``docs/planning/phases/phase-11-colab-exporter.md`` §8):

* **Export-only** — we never execute the notebook.
* **``--no-audit`` inside Colab** — the generated run writes a clean
  manifest to ``/content/run/manifest.json`` which the user pulls
  home via ``openpathai sync``.
* **Dict-level construction, not Jinja2** — the original spec
  mentioned a Jinja2 template; the initial pass hit a JSON-in-JSON
  quoting puzzle (``|tojson`` output inside a JSON string-literal
  collided with the outer quoting). Building the cells as a plain
  Python dict avoids the puzzle entirely and drops the Jinja2
  dependency. The trade-off is a slightly longer ``colab.py`` and
  no template file for callers to customise; since the notebook is
  tiny + one-shot, that's a net win.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - type-only
    from openpathai.pipeline.executor import Pipeline
    from openpathai.safety.audit import AuditEntry

__all__ = [
    "ColabExportError",
    "render_notebook",
    "write_notebook",
]


class ColabExportError(RuntimeError):
    """Raised on invalid inputs to :func:`render_notebook`."""


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #


def render_notebook(
    *,
    pipeline: Pipeline | None = None,
    pipeline_yaml: str | None = None,
    audit_entry: AuditEntry | None = None,
    openpathai_version: str | None = None,
    pip_spec: str | None = None,
) -> dict[str, Any]:
    """Return an ipynb-compliant dict that reproduces ``pipeline`` on Colab.

    At least one of ``pipeline`` / ``pipeline_yaml`` must be supplied
    (they're redundant — the YAML is embedded, the parsed pipeline is
    used for metadata). If ``pipeline`` is given without
    ``pipeline_yaml`` the YAML is regenerated via
    :func:`openpathai.cli.pipeline_yaml.dump_pipeline`.

    ``audit_entry`` is optional — when supplied, its ``run_id`` is
    embedded in the notebook metadata so the round-trip via
    ``openpathai sync`` preserves lineage.

    ``openpathai_version`` defaults to the currently-installed
    ``openpathai.__version__``. ``pip_spec`` defaults to
    ``"openpathai=={version}"``.
    """
    if pipeline is None and pipeline_yaml is None:
        raise ColabExportError(
            "render_notebook requires either `pipeline` (a parsed Pipeline) "
            "or `pipeline_yaml` (the raw YAML string) — got neither."
        )

    from openpathai import __version__ as _current_version

    if pipeline_yaml is None:
        from openpathai.cli.pipeline_yaml import dump_pipeline

        pipeline_yaml = dump_pipeline(pipeline)  # type: ignore[arg-type]

    if pipeline is None:
        from openpathai.cli.pipeline_yaml import loads_pipeline

        pipeline = loads_pipeline(pipeline_yaml)

    resolved_version = openpathai_version or _current_version
    resolved_pip_spec = pip_spec or f"openpathai=={resolved_version}"
    source_run_id = getattr(audit_entry, "run_id", "") if audit_entry else ""

    cells = [
        _markdown_cell(
            [
                "# OpenPathAI — Colab reproduction notebook\n",
                "\n",
                f"**Pipeline:** `{pipeline.id}`  \n",
                f"**Pipeline graph hash:** `{pipeline.graph_hash()}`  \n",
                f"**Source run:** `{source_run_id}`  \n",
                f"**OpenPathAI version pin:** `{resolved_version}`\n",
                "\n",
                "This notebook was generated by `openpathai export-colab`. It:\n",
                "\n",
                "1. Installs OpenPathAI at the pinned version.\n",
                "2. Writes the exact pipeline YAML used locally to `/content/pipeline.yaml`.\n",
                "3. Runs the pipeline on this Colab runtime with `--no-audit` so the manifest stays clean.\n",
                "4. Downloads the resulting `manifest.json` so you can pull it home via `openpathai sync`.\n",
                "\n",
                "**Disclaimer:** OpenPathAI produces research-grade output and is NOT a medical device. Human expert review is required for any diagnostic or treatment decision.\n",
            ]
        ),
        _code_cell(
            [
                "# Step 1 — pin pip and install OpenPathAI at the version the notebook was generated for.\n",
                "# If you are using a pre-release (no wheel on PyPI yet), replace the pinned install with:\n",
                f'#     %pip install --quiet "git+https://github.com/atultiwari/OpenPathAI.git@{resolved_version}"\n',
                '%pip install --quiet --upgrade "pip>=24"\n',
                f'%pip install --quiet "{resolved_pip_spec}"\n',
            ]
        ),
        _code_cell(
            [
                "# Step 2 — Colab convention: restart the runtime so the freshly-installed wheel is picked up.\n",
                "# Skip this cell if you installed into an existing kernel.\n",
                "import os\n",
                "if os.environ.get('COLAB_GPU') is not None:\n",
                "    from google.colab import runtime\n",
                "    runtime.restart()\n",
            ]
        ),
        _code_cell(
            [
                "# Step 3 — write the exact pipeline YAML used on the source machine.\n",
                f"pipeline_yaml = {json.dumps(pipeline_yaml)}\n",
                "with open('/content/pipeline.yaml', 'w') as fh:\n",
                "    fh.write(pipeline_yaml)\n",
                "print(f'Wrote /content/pipeline.yaml ({len(pipeline_yaml)} bytes).')\n",
            ]
        ),
        _code_cell(
            [
                "# Step 4 — run the pipeline. --no-audit keeps the Colab runtime free of a\n",
                "# transient audit DB; the local `openpathai sync` step on your laptop puts the\n",
                "# resulting run into your canonical audit store.\n",
                "!openpathai run /content/pipeline.yaml \\\n",
                "    --output-dir /content/run \\\n",
                "    --cache-root /content/cache \\\n",
                "    --no-audit\n",
            ]
        ),
        _markdown_cell(
            [
                "## Step 5 — download the manifest\n",
                "\n",
                "Run the cell below to download `/content/run/manifest.json`. On your laptop:\n",
                "\n",
                "```bash\n",
                "openpathai sync ~/Downloads/manifest.json\n",
                "```\n",
                "\n",
                "The audit DB will record this Colab run under the same `run_id` the manifest carries, and the **Runs** tab in the local GUI will list it alongside your local runs.\n",
            ]
        ),
        _code_cell(
            [
                "from google.colab import files\n",
                "files.download('/content/run/manifest.json')\n",
            ]
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
            "openpathai": {
                "generator": "openpathai.export.colab.render_notebook",
                "openpathai_version": resolved_version,
                "pipeline_id": pipeline.id,
                "pipeline_graph_hash": pipeline.graph_hash(),
                "source_run_id": source_run_id,
                "pip_spec": resolved_pip_spec,
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def write_notebook(notebook: dict[str, Any], out_path: str | Path) -> Path:
    """Write an ipynb dict to ``out_path`` as pretty-printed JSON."""
    out = Path(out_path).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as fh:
        json.dump(notebook, fh, indent=1)
        fh.write("\n")
    return out


# --------------------------------------------------------------------------- #
# Cell builders
# --------------------------------------------------------------------------- #


def _markdown_cell(source: list[str]) -> dict[str, Any]:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source,
    }


def _code_cell(source: list[str]) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }
