"""Phase 10 — ``openpathai run`` gained --workers / --parallel-mode / --snakefile."""

from __future__ import annotations

from pathlib import Path

import pytest
from typer.testing import CliRunner

from openpathai.cli.main import app

runner = CliRunner()


def _pipeline() -> str:
    return str(Path(__file__).resolve().parents[3] / "pipelines" / "supervised_synthetic.yaml")


def test_run_with_threaded_workers(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("OPENPATHAI_HOME", str(tmp_path))
    result = runner.invoke(
        app,
        [
            "run",
            _pipeline(),
            "--cache-root",
            str(tmp_path / "cache"),
            "--output-dir",
            str(tmp_path / "run"),
            "--workers",
            "4",
            "--parallel-mode",
            "thread",
            "--no-audit",
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert "parallel=thread workers=4" in result.stdout


def test_run_sequential_still_default(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("OPENPATHAI_HOME", str(tmp_path))
    result = runner.invoke(
        app,
        [
            "run",
            _pipeline(),
            "--cache-root",
            str(tmp_path / "cache"),
            "--output-dir",
            str(tmp_path / "run"),
            "--no-audit",
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert "parallel=sequential" in result.stdout


def test_run_bad_parallel_mode_exits_2(tmp_path: Path) -> None:
    result = runner.invoke(
        app,
        [
            "run",
            _pipeline(),
            "--cache-root",
            str(tmp_path / "cache"),
            "--output-dir",
            str(tmp_path / "run"),
            "--parallel-mode",
            "distributed",
            "--no-audit",
        ],
    )
    assert result.exit_code == 2


def test_run_snakefile_exports_without_running(tmp_path: Path) -> None:
    out = tmp_path / "demo.smk"
    result = runner.invoke(
        app,
        [
            "run",
            _pipeline(),
            "--snakefile",
            str(out),
            "--no-audit",
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert out.is_file()
    body = out.read_text(encoding="utf-8")
    assert body.startswith("# Generated by openpathai.pipeline.snakemake")
    assert "rule all:" in body
    # --snakefile is export-only: no manifest written under --output-dir.
    assert "manifest:" not in result.stdout


def test_run_reference_pipeline_exits_zero(tmp_path: Path) -> None:
    ref = Path(__file__).resolve().parents[3] / "pipelines" / "supervised_tile_classification.yaml"
    result = runner.invoke(
        app,
        [
            "run",
            str(ref),
            "--cache-root",
            str(tmp_path / "cache"),
            "--output-dir",
            str(tmp_path / "run"),
            "--parallel-mode",
            "thread",
            "--workers",
            "2",
            "--no-audit",
        ],
    )
    assert result.exit_code == 0, result.stdout
    assert "supervised-tile-classification" in result.stdout
