"""Snakefile exporter — write a pipeline as Snakemake rules.

Phase 10 ships the exporter as an **export-only** integration: we
generate a self-contained Snakefile that users can run with their own
``snakemake`` CLI. OpenPathAI itself never imports or subprocesses
Snakemake, so Snakemake stays a strictly opt-in dependency.

The generated Snakefile shells back into ``openpathai run`` for each
rule so the node registry, cache, and manifest machinery stay single-
sourced. Per-slide fan-out lowers to a Snakemake ``expand`` over the
cohort's slide ids.
"""

from __future__ import annotations

from pathlib import Path

from openpathai.pipeline.executor import Pipeline

__all__ = [
    "generate_snakefile",
    "write_snakefile",
]


_HEADER = """# Generated by openpathai.pipeline.snakemake — do not edit by hand.
#
# Run with:
#     snakemake --snakefile <this file> --cores N
#
# Every rule shells back into `openpathai run` so the node registry,
# content-addressable cache, and run manifest stay single-sourced.

from pathlib import Path
"""


def _quote(value: str) -> str:
    """Python-style single-quoted string literal, escape-safe."""
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def generate_snakefile(pipeline: Pipeline) -> str:
    """Return a Snakefile source that runs ``pipeline`` via Snakemake.

    The output is a plain ``str`` — no filesystem I/O, no Snakemake
    dependency. Callers typically pipe the result through
    :func:`write_snakefile` or just ``print`` it.

    The generated file declares one rule per pipeline step, plus a
    top-level ``rule all`` that depends on the terminal step's output.
    Cohort fan-out lowers to ``expand("{slide_id}/…", slide_id=SLIDES)``
    so the user can provide ``SLIDES=[…]`` on the command line
    (``snakemake --config SLIDES=…``) or via a sidecar config file.
    """
    lines: list[str] = [_HEADER, ""]
    lines.append(f"# Pipeline id:          {pipeline.id}")
    lines.append(f"# Pipeline graph hash:  {pipeline.graph_hash()}")
    lines.append(f"# Mode:                 {pipeline.mode}")
    if pipeline.cohort_fanout:
        lines.append(f"# Cohort fan-out step:  {pipeline.cohort_fanout}")
    if pipeline.max_workers:
        lines.append(f"# Suggested workers:    {pipeline.max_workers}")
    lines.append("")

    fanout = pipeline.cohort_fanout
    if fanout is not None:
        lines.append("# Slide ids are supplied via --config SLIDES='a,b,c' or a config file.")
        lines.append("SLIDES = config.get('SLIDES', '')")
        lines.append("if isinstance(SLIDES, str):")
        lines.append("    SLIDES = [s for s in SLIDES.split(',') if s]")
        lines.append("if not SLIDES:")
        lines.append(
            "    raise ValueError('Pass --config SLIDES=\"id1,id2,…\" for a fan-out pipeline.')"
        )
        lines.append("")
        lines.append(f"PIPELINE_YAML = {_quote(pipeline.id)}")
        lines.append("")
        terminal_id = pipeline.steps[-1].id
        lines.append("rule all:")
        lines.append(
            f"    input:\n        expand('{{slide_id}}/{terminal_id}.done', slide_id=SLIDES)"
        )
        lines.append("")
        for step in pipeline.steps:
            deps = _deps(step, pipeline)
            input_lines = [f"        '{{slide_id}}/{dep}.done'" for dep in sorted(deps)]
            lines.append(f"rule {step.id}:")
            if input_lines:
                lines.append("    input:")
                lines.extend(f"{li}," for li in input_lines[:-1])
                lines.append(input_lines[-1])
            lines.append("    output:")
            lines.append(f"        touch('{{slide_id}}/{step.id}.done')")
            lines.append("    shell:")
            lines.append(
                "        'openpathai run ' + PIPELINE_YAML "
                "+ ' --step ' + {step_id} + ' --slide ' + wildcards.slide_id".replace(
                    "{step_id}", _quote(step.id)
                )
            )
            lines.append("")
    else:
        terminal_id = pipeline.steps[-1].id
        lines.append(f"PIPELINE_YAML = {_quote(pipeline.id)}")
        lines.append("")
        lines.append("rule all:")
        lines.append(f"    input: '{terminal_id}.done'")
        lines.append("")
        for step in pipeline.steps:
            deps = _deps(step, pipeline)
            lines.append(f"rule {step.id}:")
            if deps:
                lines.append("    input:")
                sorted_deps = sorted(deps)
                for d in sorted_deps[:-1]:
                    lines.append(f"        '{d}.done',")
                lines.append(f"        '{sorted_deps[-1]}.done'")
            lines.append("    output:")
            lines.append(f"        touch('{step.id}.done')")
            lines.append("    shell:")
            lines.append(
                "        'openpathai run ' + PIPELINE_YAML + ' --step ' + " + _quote(step.id)
            )
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def write_snakefile(pipeline: Pipeline, path: str | Path) -> Path:
    """Write :func:`generate_snakefile` output to ``path`` and return it."""
    out = Path(path).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate_snakefile(pipeline), encoding="utf-8")
    return out


def _deps(step, pipeline: Pipeline) -> set[str]:
    """Return the upstream step ids this step depends on."""
    import re

    pattern = re.compile(r"^@(?P<step>[A-Za-z_][A-Za-z0-9_]*)")
    out: set[str] = set()
    for value in step.inputs.values():
        if isinstance(value, str):
            m = pattern.match(value)
            if m:
                out.add(m.group("step"))
    return out
